export const GAMES = [
  {
    id: 'flappy',
    name: 'Flappy Bird',
    shortName: 'Flappy',
    path: '/game',
    howToPath: '/howto/flappy',
    emoji: '🐦',
    cardClass: 'card-score',
    blurb: 'Tap or press Space to flap. Clear 20 pipes to go up a level, then beat all 5 levels to win.',
    steps: [
      { emoji: '👆', title: 'Tap or Space', text: 'Give the bird a flap whenever it starts to fall.', cardClass: 'card-tap' },
      { emoji: '🌿', title: 'Dodge pipes', text: 'Fly through the green openings. Don’t bump the edges!', cardClass: 'card-dodge' },
      { emoji: '🏁', title: 'Beat 5 levels', text: 'Each pipe is a point. Pass 20 pipes to level up — later levels are faster and tighter. Clear all 5 to win!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'dino',
    name: 'Dino Runner',
    shortName: 'Dino',
    path: '/game/dino',
    howToPath: '/howto/dino',
    emoji: '🦖',
    cardClass: 'card-dino',
    blurb: 'Tap or press Space to jump from the ground. You have 3 lives — clear 20 obstacles to go up a level, then beat all 5 levels to win.',
    steps: [
      { emoji: '👆', title: 'Tap or Space', text: 'Jump only from the ground — tapping in the air will not keep you up. Hold a little longer for a higher hop.', cardClass: 'card-tap' },
      { emoji: '🌵', title: 'Read the obstacle', text: 'Leap over cacti and low birds. Stay on the ground to run under high pterodactyls.', cardClass: 'card-dino' },
      { emoji: '❤️', title: 'Three lives', text: 'A bump costs one life. You get two more tries, then the run is over. Pass 20 obstacles to level up — clear all 5 to win!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'chase',
    name: 'Chase',
    shortName: 'Chase',
    path: '/game/chase',
    howToPath: '/howto/chase',
    emoji: '🏃',
    cardClass: 'card-chase',
    blurb: 'Grab the stars and stay ahead of the chasers. You have 3 lives — a new chaser joins every level. Clear all 10 levels to win.',
    steps: [
      { emoji: '👆', title: 'Move around', text: 'Slide a finger, move the mouse, or use the arrow keys / WASD.', cardClass: 'card-tap' },
      { emoji: '⭐', title: 'Grab the stars', text: 'Collect every yellow star on the field. Weave around the bushes if you need a shortcut.', cardClass: 'card-chase' },
      { emoji: '👾', title: 'Don’t get tagged', text: 'Chasers hunt you down. You have 3 lives. Each new level adds one more chaser, a little slower as the pack grows. Clear all 10 to win!', cardClass: 'card-score' },
    ],
  },
  {
    id: '2048',
    name: '2048',
    shortName: '2048',
    path: '/game/2048',
    howToPath: '/howto/2048',
    emoji: '🔢',
    cardClass: 'card-merge',
    blurb: 'Slide tiles, merge matching numbers, and chase a huge high score.',
    steps: [
      { emoji: '➡️', title: 'Slide the grid', text: 'Use arrow keys, WASD, or a swipe to move every tile.', cardClass: 'card-tap' },
      { emoji: '➕', title: 'Merge matches', text: 'When two tiles with the same number meet, they become one bigger tile.', cardClass: 'card-merge' },
      { emoji: '🎯', title: 'Chase 2048', text: 'Reach 2048, then keep going. Every merge adds to your score.', cardClass: 'card-score' },
    ],
  },
  {
    id: 'whack',
    name: 'Whack-a-Mole',
    shortName: 'Whack',
    path: '/game/whack',
    howToPath: '/howto/whack',
    emoji: '🔨',
    cardClass: 'card-whack',
    blurb: 'Tap moles as they pop up. Fast reflexes, instant bonks, big scores.',
    steps: [
      { emoji: '🕳️', title: 'Watch the holes', text: 'Moles peek out for just a moment. Don’t blink!', cardClass: 'card-tap' },
      { emoji: '👆', title: 'Tap to bonk', text: 'Hit a mole while it’s up. You’ll see a pop and hear a bonk.', cardClass: 'card-whack' },
      { emoji: '⏱️', title: 'Beat the clock', text: 'Set the time limit, then tap moles before they hide. Every hit is a point.', cardClass: 'card-score' },
    ],
  },
  {
    id: 'pong',
    name: 'Pong',
    shortName: 'Pong',
    path: '/game/pong',
    howToPath: '/howto/pong',
    emoji: '🏓',
    cardClass: 'card-pong',
    blurb: 'One player vs the computer. Move your paddle, bounce the ball, first to 5 wins.',
    steps: [
      { emoji: '👆', title: 'Move your paddle', text: 'Slide a finger, move the mouse, or use the arrow keys. Your paddle is the pink one on the left.', cardClass: 'card-tap' },
      { emoji: '🏓', title: 'Hit the ball', text: 'Bounce it past the blue computer paddle. Aim with the edge of your paddle to send it up or down.', cardClass: 'card-pong' },
      { emoji: '⭐', title: 'First to 5', text: 'Every ball the computer misses is a point. Reach 5 before the CPU does!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'breakout',
    name: 'Breakout',
    shortName: 'Breakout',
    path: '/game/breakout',
    howToPath: '/howto/breakout',
    emoji: '🧱',
    cardClass: 'card-breakout',
    blurb: 'Aim the ball, bounce it off the paddle, and smash every brick. Steeper angles, smarter shots.',
    steps: [
      { emoji: '🎯', title: 'Aim your shot', text: 'Move the paddle to point the dotted line. That line is the path the ball will take.', cardClass: 'card-tap' },
      { emoji: '📐', title: 'Use the angle', text: 'Hit the ball with the edge of the paddle to send it sideways. Bank it off a wall to reach tricky bricks.', cardClass: 'card-breakout' },
      { emoji: '🧱', title: 'Clear the wall', text: 'Break every brick to go up a level. Combos and bank shots score extra. Don’t let the ball fall!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'starwaves',
    name: 'Star Waves',
    shortName: 'Star Waves',
    path: '/game/starwaves',
    howToPath: '/howto/starwaves',
    emoji: '🚀',
    cardClass: 'card-starwaves',
    blurb: 'Move your ship, blast the star blobs, and clear each wave before they reach you.',
    steps: [
      { emoji: '🚀', title: 'Steer your ship', text: 'Slide a finger, move the mouse, or use the arrow keys along the bottom.', cardClass: 'card-tap' },
      { emoji: '⭐', title: 'Blast the blobs', text: 'Tap the game or press Space to shoot. Back-row blobs are worth extra points.', cardClass: 'card-starwaves' },
      { emoji: '🌊', title: 'Clear the wave', text: 'Zap every blob to start a faster wave. Dodge their sparkles — you have 3 lives!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'bubble',
    name: 'Bubble Shooter',
    shortName: 'Bubble',
    path: '/game/bubble',
    howToPath: '/howto/bubble',
    emoji: '🫧',
    cardClass: 'card-bubble',
    blurb: 'Aim the cannon, match 2 or more bubbles of the same color, and clear the cluster before it drops.',
    steps: [
      { emoji: '🎯', title: 'Aim and shoot', text: 'Move the mouse or a finger, or use the arrow keys. Tap or press Space to send a bubble.', cardClass: 'card-tap' },
      { emoji: '🫧', title: 'Match two', text: 'Hit a group of the same color. Two or more pop, and leftover bubbles can fall.', cardClass: 'card-bubble' },
      { emoji: '⬇️', title: 'Watch the drop', text: 'After a few shots, a new row slides in. Don’t let bubbles cross the pink line!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'snake',
    name: 'Snake',
    shortName: 'Snake',
    path: '/game/snake',
    howToPath: '/howto/snake',
    emoji: '🐍',
    cardClass: 'card-snake',
    blurb: 'Steer the snake, eat apples, and grow. Don’t hit a wall or your own tail.',
    steps: [
      { emoji: '➡️', title: 'Steer', text: 'Use arrow keys, WASD, or a swipe. You can’t turn straight back on yourself.', cardClass: 'card-tap' },
      { emoji: '🍎', title: 'Eat apples', text: 'Each pink apple makes the snake longer and adds to your score.', cardClass: 'card-snake' },
      { emoji: '🏁', title: 'Keep growing', text: 'Every 5 apples you speed up a level. Don’t bump the edge or your tail!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'tictactoe',
    name: 'Tic Tac Toe',
    shortName: 'Tic Tac Toe',
    path: '/game/tictactoe',
    howToPath: '/howto/tictactoe',
    emoji: '❌',
    cardClass: 'card-tictactoe',
    blurb: 'You are X. Get three in a row before the computer. First to 5 wins the match.',
    steps: [
      { emoji: '👆', title: 'Tap a square', text: 'Place your X in an empty square. Numbers 1 to 9 work too.', cardClass: 'card-tap' },
      { emoji: '❌', title: 'Make three in a row', text: 'Line up three X’s across, down, or diagonally. Block the computer’s O’s too!', cardClass: 'card-tictactoe' },
      { emoji: '⭐', title: 'First to 5', text: 'Each round you win is a point. Reach 5 before the computer does!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'connectfour',
    name: 'Connect Four',
    shortName: 'Connect Four',
    path: '/game/connectfour',
    howToPath: '/howto/connectfour',
    emoji: '🟡',
    cardClass: 'card-connectfour',
    blurb: 'Drop discs into a column and get four in a row before the computer. First to 5 wins the match.',
    steps: [
      { emoji: '👆', title: 'Tap a column', text: 'Discs fall to the lowest open slot. Numbers 1 to 7 work too.', cardClass: 'card-tap' },
      { emoji: '🟡', title: 'Make four in a row', text: 'Line up four pink discs across, down, or diagonally. Block the computer’s yellow discs too!', cardClass: 'card-connectfour' },
      { emoji: '⭐', title: 'First to 5', text: 'Each round you win is a point. Reach 5 before the computer does!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'chess',
    name: 'Chess',
    shortName: 'Chess',
    path: '/game/chess',
    howToPath: '/howto/chess',
    emoji: '♟️',
    cardClass: 'card-chess',
    blurb: 'Play the computer, or make a room and share the link so a friend can join. Checkmate the king. First to 3 beats the computer.',
    steps: [
      { emoji: '👆', title: 'Tap, then move', text: 'Tap one of your pieces. Dots show where it can go. Tap a dotted square to move — or tap a circled piece to capture it.', cardClass: 'card-tap' },
      { emoji: '♟️', title: 'How pieces move', text: 'Pawns step forward and capture diagonally. Knights jump. Bishops go diagonal, rooks go straight, and the queen does both. The king moves one square. The king can also hop two squares to castle.', cardClass: 'card-chess' },
      { emoji: '♔', title: 'Checkmate to win', text: 'If someone attacks your king, that’s check — you must get out of it. Trap their king so it cannot escape to win. Vs the computer, first to 3 wins the match!', cardClass: 'card-score' },
      { emoji: '🔗', title: 'Play a friend', text: 'Tap Play a friend to make a room, then copy the link or code. Your friend opens it and you play live — you are White, they are Black.', cardClass: 'card-chess' },
    ],
  },
  {
    id: 'ludo',
    name: 'Ludo',
    shortName: 'Ludo',
    path: '/game/ludo',
    howToPath: '/howto/ludo',
    emoji: '🎲',
    cardClass: 'card-ludo',
    blurb: 'Roll the dice, race your four tokens around the board, and get them all home before the computer.',
    steps: [
      { emoji: '🎲', title: 'Roll a 6 to start', text: 'Tap the dice. A 6 lets a token leave your yard, and you get another roll. Space also rolls.', cardClass: 'card-tap' },
      { emoji: '🏃', title: 'Race around', text: 'Tap a glowing token to move it. Land on someone (not on a star) to send them back to their yard. Exact rolls get you home.', cardClass: 'card-ludo' },
      { emoji: '🏠', title: 'Get all four home', text: 'Each token home scores 25, each capture 10, and finishing first adds 100. Beat Green, Yellow, and Blue!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'towerdefense',
    name: 'Tower Defense',
    shortName: 'Towers',
    path: '/game/towerdefense',
    howToPath: '/howto/towerdefense',
    emoji: '🏰',
    cardClass: 'card-towerdefense',
    blurb: 'Place towers along the path, stop the blobs, and clear all 30 waves before they reach the castle. Later waves hit harder and faster.',
    steps: [
      { emoji: '👆', title: 'Pick, then place', text: 'Tap a tower on the right — Dart, Frost, or Boom. Then tap a grass square beside the path. Keys 1, 2, and 3 work too.', cardClass: 'card-tap' },
      { emoji: '🏰', title: 'Guard the path', text: 'Blobs walk the sandy trail. Dart hits one, Frost slows them, Boom splashes a group. Spend gold from each KO to build more.', cardClass: 'card-towerdefense' },
      { emoji: '🏁', title: 'Beat 30 waves', text: 'You have 8 lives. A blob that reaches the pink castle costs a life — bosses cost 2. Clear every wave to win, and chase a huge score!', cardClass: 'card-score' },
    ],
  },
  {
    id: 'simon',
    name: 'Simon Says',
    shortName: 'Simon',
    path: '/game/simon',
    howToPath: '/howto/simon',
    emoji: '🎵',
    cardClass: 'card-simon',
    blurb: 'Watch the colored lights, tap them back in order, and see how long a sequence you can remember.',
    steps: [
      { emoji: '👀', title: 'Watch the lights', text: 'Simon lights up a color and plays a tone. Remember the order.', cardClass: 'card-tap' },
      { emoji: '👆', title: 'Repeat the sequence', text: 'Tap the same colors in the same order. Q W A S or 1 to 4 work too.', cardClass: 'card-simon' },
      { emoji: '🧠', title: 'Go longer', text: 'Each round adds one more color and speeds up a little. One miss ends the game!', cardClass: 'card-score' },
    ],
  },
];

export const DEFAULT_GAME = 'flappy';

export function isValidGame(id) {
  return GAMES.some((game) => game.id === id);
}

export function getGame(id) {
  return GAMES.find((game) => game.id === id) || null;
}
